spring:
  config:
    activate:
      on-profile:
      - prod
  application:
    name: pharmacy-authentication
  datasource:
    url: jdbc:h2:mem:securitydb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect    
server:
  port: 8080        
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER}:8761/eureka/
      
---

spring:
  config:
    activate:
      on-profile:
      - test
  application:
    name: pharmacy-authentication
  datasource:
    url: jdbc:h2:mem:securitydb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect  
server:
  port: 8090        
eureka:
  client:
    enabled: false
    
---


spring:
  config:
    activate:
      on-profile:
      - dev
  application:
    name: pharmacy-authentication
  h2:
    console:
      enabled: true  
  datasource:
    url: jdbc:h2:mem:securitydb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect  
server:
  port: 8090        
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/               